/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 KA10054.glb --transform --simplify 
Files: KA10054.glb [22.64MB] > /Users/mac/Dropbox/Code Assets/kanak/public/KA10054-transformed.glb [538.87KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/KA10054-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tray.geometry} material={materials.StingrayPBS2} />
      <mesh geometry={nodes.lid.geometry} material={materials.StingrayPBS1} />
    </group>
  )
}

useGLTF.preload('/KA10054-transformed.glb')
