/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cuplid-clean-transformed.glb --transform 
Files: cuplid-clean-transformed.glb [152.08KB] > /Users/mac/Dropbox/Code Assets/kanak/public/glb/cuplid-clean-transformed-transformed.glb [145.06KB] (5%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cuplid-clean-transformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SoftFBXASC032drinkFBXASC032glass.geometry} material={materials.StingrayPBS1} />
    </group>
  )
}

useGLTF.preload('/cuplid-clean-transformed-transformed.glb')
