/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 EDU.glb --transform
Files: EDU.glb [26.6MB] > /Users/mac/Dropbox/Code Assets/kanak/public/EDU-transformed.glb [577.28KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/EDU-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.three_compartment_tray.geometry} material={materials.StingrayPBS1} />
    </group>
  )
}

useGLTF.preload('/EDU-transformed.glb')
