/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 EDU.glb --transform
Files: EDU.glb [26.6MB] > /Users/mac/Dropbox/Code Assets/kanak/public/EDU-transformed.glb [577.28KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FoodContainer(props) {
  const { nodes } = useGLTF('/glb/food-container-clean.glb')
  console.log(props.material)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.three_compartment_tray.geometry} castShadow={true} receiveShadow={true}>
        {props.material}
      </mesh>
    </group>
  )
}

useGLTF.preload('/EDU-transformed.glb')
