/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 PC6200.glb --transform 
Files: PC6200.glb [2.21MB] > /Users/mac/Dropbox/Code Assets/kanak/public/PC6200-transformed.glb [114.84KB] (95%)
*/

import { useGLTF } from '@react-three/drei'
let path;
export function GetModel({...props}) {
  path = props.file
  const { nodes } = useGLTF(props.file) 
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Scene.children[0].geometry} material={!props.material && nodes.Scene.children[0].material}>
        {props.material && props.material}
      </mesh>
    </group>
  )
}

useGLTF.preload(path)
