/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 PC6200.glb --transform
Files: PC6200.glb [2.21MB] > /Users/mac/Dropbox/Code Assets/kanak/public/PC6200-transformed.glb [114.84KB] (95%)
*/

import { useGLTF } from '@react-three/drei'
let path;

export function GetModel(props) {
  path = props.file
  const { nodes } = useGLTF(props.file)
  return (
    <group {...props} dispose={null}>
      {nodes.Scene.children.map((item, idx) => (
        <mesh castShadow geometry={item.geometry} name={props.name} material={!props.material && item.material} key={idx}>
          {props.material && props.material}
        </mesh>
      ))}
    </group>
  )
}

useGLTF.preload(path)
